### ISSUE TITLE
Unable to open settings

### ISSUE THREAD

**Issue by bvn13** [raujonas/executor#22]
Clicking on any output string does not bring the settings up. Should it?

**Comment by raujonas** [comment]
Hi @bvn13!

At the moment this is the expected behavior because this functionality is not implemented. The settings have to be openend via the gnome extensions application or via the installed extensions on the gnome extension website.

**Comment by G-dH** [comment]
Hi @raujonas, this is very easy to implement and I think it would be worth it.

    const Me         = ExtensionUtils.getCurrentExtension();
    const ExtManager = Main.extensionManager;

and connect `button-press-event` signals of those St.BoxLayout widgets to the callback function with this:

    ExtManager.openExtensionPrefs(Me.metadata.uuid, '', {});

**Comment by raujonas** [comment]
I'll have a look into this now, thanks for your hints.

Do you know if it is possible to pass a parameter to the extension settings or call a specific method there? This way we could open the "right" tab if one clicks on the right St.BoxLayout in the bar.

**Comment by G-dH** [comment]
I think the easist way would be to use gsettings key with position number, this can be read from both prefs and extension.

**Comment by raujonas** [comment]
Okay I'm somehow still failing with getting the click signal, this should work right? Currently I cannot see the log output.

```
this.locations[position].box = new St.BoxLayout({ style_class: 'panel-button' });
...
this.locations[position].box.connect(
            'button-press-event', () => {
                log('test')
            }
        );
```

**Comment by G-dH** [comment]
Set the box: `reactive: true` ;)

**Comment by raujonas** [comment]
Thanks, that worked! I implemented the changes in #27 if you want to have a look. Feel free to make a comment if you see any room for improvement. The prefs window does now also remember the last selected tab which is nice imo :blush:

**Comment by raujonas** [comment]
Okay I have to take a look again, because setting the key on close of the prefs window is not working on gnome 40..

**Comment by G-dH** [comment]
You can use notebook's signal `switch-page` and write it immediately.

**Comment by raujonas** [comment]
I tried this first like this:
```
this.notebook.connect('switch-page', () => {
   log(this.notebook.get_current_page());
})
```
But there's always the previous index returned, like when left is selected and I click on the center tab, then it returns 0. If I click then on the right tab it returns 1. Do you know what is my mistake here?

**Comment by G-dH** [comment]
You get the index from the time this function was built..
Read the documentation, you get the index directly from the event:

    notebook.connect('switch-page', (notebook, page, index) => {
        ...
     });

**Comment by raujonas** [comment]
Sorry, the documentation I always look into does not contain the third parameter: https://gjs-docs.gnome.org/gtk40~4.0.3/gtk.notebook#signal-switch-page I tried with these two parameters before and it did not work because I missed the third one obviously :(
`switch-page(page, page_num) `

Which documentation are you using and can you please send me a link?

Now it works perfectly!

**Comment by G-dH** [comment]
I use what google find first, mostly original for c :)
https://developer.gnome.org/gtk4/stable/GtkNotebook.html#GtkNotebook-switch-page
An event always contains the object which received the signal.

**Comment by raujonas** [comment]
That's good to know. I'll merge it and make a new release then. Thanks for your help again :blush:

**Comment by G-dH** [comment]
I just noticed that the new Executor is already in my system, that was fast 👍🏻 :)

**Comment by G-dH** [comment]
But there is a race condition problem - the page key might be (and in my case is every time) written to the gsettings after prefs is reading the value and therefore opens the previous page. I would wait for 'changed:location' signal..

**Comment by raujonas** [comment]
Could you please elaborate this a little bit more? I have not recognized any issues so far.

**Comment by G-dH** [comment]
this.settings.set_int('location', position);
    ExtManager.openExtensionPrefs(Me.metadata.uuid, '', {});

This is **not** synchronous operation, prefs can read the key before new value is actually written.

**Comment by raujonas** [comment]
Okay understood, thanks. The documentation I found says: 

```
 set_int(key, value)[source]
    Parameters:	

        key (str) – the name of the key to set
        value (int) – the value to set it to

    Returns:	

    **True if setting the key succeeded, False if the key was not writable**
    Return type:	

    bool
```
So this should be sufficient, do you agree?
```
if (this.settings.set_int('location', position)) {
      ExtManager.openExtensionPrefs(Me.metadata.uuid, '', {});
}
```

Could you please do me the favour to test this on your system? I cannot reproduce the behavior.

**Comment by G-dH** [comment]
This will not change a thing, the problem is asynchronous write to disk. Even the signal is emitted before the new key is readable. Wait for disk sync is overkill, a little delay will fix it for most cases:

        this.locations[position].locationClicked = this.locations[position].box.connect(
            'button-press-event', () => {
                this.settings.set_int('location', position);
                GLib.timeout_add(
                        GLib.PRIORITY_DEFAULT,
                        100,
                        () => {
                            ExtManager.openExtensionPrefs(Me.metadata.uuid, '', {}); 
                        });
            }
        );

**Comment by raujonas** [comment]
Okay thanks for the explanation and your testing! I added this (https://github.com/raujonas/executor/commit/ea8d827d0f86fa6e8622a32b4656077ca04c0d6c) and will make a new release if you agree.

**Comment by G-dH** [comment]
It work for me. My /home is on HDD now otherwise I probably wouldn't notice.

**Comment by raujonas** [comment]
Already active on the store, they are so fast today!

**Comment by G-dH** [comment]
Faster every day.. :) Have you tried [my extension](https://github.com/G-dH/custom-hot-corners-extended/tree/devel) yet? I need some feedback ;)
