### ISSUE TITLE
signal: instance has no handler with id ...

### ISSUE THREAD

**Issue by G-dH** [raujonas/executor#28]
When disabling Executor:

    ../../../gobject/gsignal.c:2736: instance '0x558f1fce2c30' has no handler with id '241808'
    ../../../gobject/gsignal.c:2736: instance '0x558f1fce2c30' has no handler with id '241848'
    ../../../gobject/gsignal.c:2736: instance '0x558f1fce2c30' has no handler with id '241863'
    Executor stopped

**Comment by raujonas** [comment]
My bad, I disconnected the signal from the wrong object. Fixed now.
```
gnome-shell[2225]: Executor enabled
gnome-shell[2225]: Executor stopped
gnome-shell[2225]: Executor enabled
gnome-shell[2225]: Executor stopped
gnome-shell[2225]: Executor enabled
```
