### ISSUE TITLE
Multimonitor executor?

### ISSUE THREAD

**Issue by ser** [raujonas/executor#38]
Multimonitor extension is really helpful to have several status areas available. I don't see any way to make use of that with executor unfortunately, it works on one monitor only. Any idea how to make use of more than one of them?

**Comment by raujonas** [comment]
Hi @ser. Sorry for the late reply. Could you please link the extension you are using? I asume that you can use another panel than the main panel, but I've to check that. Currently it is hardcoded for the main panel:

`Main.panel['_' + location.name + 'Box'].insert_child_at_index(location.box, location.lastIndex);`

**Comment by ser** [comment]
I used to use https://github.com/spin83/multi-monitors-add-on

But for last three days not anymore, as I started to use Gnome 40 and that extension stopped to work - there is an issue reported though so I hope it will be working back again soon.

**Comment by ser** [comment]
Hi, multimonitor extension is working again for gnome 40/41:

https://github.com/realh/multi-monitors-add-on

It would be really cool if executor could use it!

**Comment by ser** [comment]
I'm closing it temporary, as the multimonitor extension is currently in a pretty bad shape. I will re-open when it will fully work again.
