### ISSUE TITLE
Command execution does not work under nixos

### ISSUE THREAD

**Issue by maralorn** [raujonas/executor#39]
Hey there,

this looks like a really nice plugin. Sadly when I run it under gnome 40 on nixos, I get no errors, but no messages appear anywhere in the status bar no matter what I do. Is this plugin tested and supposed to be working on gnome 40?

**Comment by raujonas** [comment]
Hi @maralorn. Support for gnome 40 is already implemented and tested on Fedora 34. I'll check again on a fresh system if it still works there or if there are any new issues.

**Comment by piegamesde** [comment]
I can reproduce on a clean NixOS VM, but on Arch Linux it works. It would be cool to have some more error messages in case of failure.

**Comment by maralorn** [comment]
Thank you for your reply @raujonas. I think the cause is this line. https://github.com/raujonas/executor/blob/9aa3cfe6b9a0735c4abb133595d2e16a8f650a32/extension.js#L228 

We don‘t have `/bin/bash` under nixos. I think `bash` would work, `/bin/sh` or `/usr/bin/env bash` would also work. Nixos is a bit picky with this.^^

**Comment by maralorn** [comment]
If you don‘t want to introduce a fix for this in executor we can apply a fix in our distribution.

**Comment by maralorn** [comment]
If other nixos users want to run executor I have a quickfix here:
```
    executor = self.gnomeExtensions.executor.overrideAttrs (old: {
      buildCommand = old.buildCommand + ''
        substituteInPlace $out/share/gnome-shell/extensions/executor@raujonas.github.io/extension.js --replace "'/bin/bash'" "'/usr/bin/env', 'bash'"
      '';
    });
```

**Comment by raujonas** [comment]
Thanks for debugging this :blush: I would be happy to provide a fix for this, but I'm still thinking what the best solution might be here. I think that there are two ways:

1) Checking automatically on init if the system has `/bin/bash`, and if not, using `/usr/bin/env bash` (or what you think is the best option). If there are issues with other distributions in the feature, we could just add a third option here and take the first one which exists on the system? This is propably the fastest solution for now.
2) A new setting in the preferences window where you can add custom shell locations and select one? This would be more complex but would give the users more flexibility, but would also require more work.

I think I would prefer option 1 for now, what do you think?

**Comment by maralorn** [comment]
>     1. Checking automatically on init if the system has `/bin/bash`, and if not, using `/usr/bin/env bash` (or what you think is the best option). If there are issues with other distributions in the feature, we could just add a third option here and take the first one which exists on the system? This is propably the fastest solution for now.

The question is if you even need the logic check on startup. I don‘t know of a system where `/usr/bin/env bash` does not work. But yeah, this solution would be completely fine.

>     2. A new setting in the preferences window where you can add custom shell locations and select one? This would be more complex but would give the users more flexibility, but would also require more work.

I have thought of that option too. Either seem fine. Having the ability to use zsh or something like that would sure be nice, but I think totally unnecessary, because you can already execute arbitrary commands. So the extra flexibility is not needed.

I‘d go with something like 1.

**Comment by piegamesde** [comment]
`/usr/bin/env` is usually used when modifications to the environment of the child process are needed or when the path must be absolute (for example in shell shebangs). Neither case applies here, and thus simply writing `bash` should be sufficient and work on all platforms.

**Comment by maralorn** [comment]
> Neither case applies here

Are you sure? I know multiple programing languages in which exec does not do a `PATH` lookup. Haven‘t tried it in this case though.

**Comment by piegamesde** [comment]
Yes, this is not an `exec`, this is a [GIO subprocess](https://developer.gnome.org/gio/2.56/GSubprocess.html) spawn.

> As a matter of principle, GSubprocess has no API that accepts shell-style space-separated strings. It will, however, match the typical shell behaviour of searching the PATH for executables that do not contain a directory separator in their name.

**Comment by raujonas** [comment]
> and thus simply writing bash should be sufficient and work on all platforms.

Okay I tried just `bash` now and it works fine on Ubuntu! Would you mind testing the above linked PR on your system?

I'll then create a new release :blush:

**Comment by maralorn** [comment]
Works fine! thx!

**Comment by raujonas** [comment]
It's now available in the store! Thanks again :)
