### ISSUE TITLE
Add option to disable settings window popup when clicking top bar

### ISSUE THREAD

**Issue by rxvisser** [raujonas/executor#41]
Using executor in combination with programs that have frequently-clicked elements near Gnome's top bar causes annoyance when misclicking on executor output, which opens the extension's settings window.

An example: tabs in a web browser with no title bar.
Half my top bar is executor output, so this happens often enough that it's a nuisance.

BTW, this extension is great, thank you for making/maintaining it.

**Comment by raujonas** [comment]
Hi @rxvisser. Thanks for your warm words, it means a lot to me that you find the extension useful :blush: I'll add an option to disable this feature next, but it might take a few days.

**Comment by raujonas** [comment]
Hi @rxvisser, sorry again for the delay! I had finally some spare time and I just had a look into this. You could check out the new pull request #43 if you like and test it on your system before I merge it, that would be super helpful but it's not a must :blush: I'll test it either way on my system for some days to make sure that there are no side effects and then I'll make a new release on the extensions website!

Thanks again for your contribution to the project, I hope this will fix your issue.

**Comment by rxvisser** [comment]
Hey @raujonas, please don't let me make you worry about timelines for the nice open source software you provide for free :grinning:
I tested the branch from #43 on my system (Gnome 40.3.0) and the feature behaves exactly as expected.

I did notice one quirk however: If the extension settings window is open on the 'General' tab with the toggle to 'on', clicking on output will open a second extension settings window that is completely frozen. You have to close the older extensions settings window (or switch it to any of the other tabs) to make the new settings window responsive.

The quirk does not affect me at all since I have the toggle set to 'off', but even people who have it 'on' should maybe not be opening multiple settings windows. Thought I'd mention it regardless.

Thanks again for working on this!

**Comment by raujonas** [comment]
@rxvisser thanks for testing this! I noticed this strange behavior too when I worked on this. But then I realized that it is the same in the old version, so I'll make a new ticket for that :blush:
