### ISSUE TITLE
Unhandled promise rejection for commands using <executor.markup.true>

### ISSUE THREAD

**Issue by mkalinski** [raujonas/executor#58]
Somehow #53 returned.

```
Jan 06 19:58:38 mk gnome-shell[3098]: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
                                        execCommand@/home/mk/.local/share/gnome-shell/extensions/executor@raujonas.github.io/extension.js:247:27
                                        handleCurrentQueue@/home/mk/.local/share/gnome-shell/extensions/executor@raujonas.github.io/extension.js:233:10
                                        handleCurrentQueue/<@/home/mk/.local/share/gnome-shell/extensions/executor@raujonas.github.io/extension.js:238:22
```

It looks like it only happens for commands that include the [`<executor.markup.true>`](https://raujonas.github.io/executor/docs/configuration/custom-markup/) string in output, whether or not any markup is actually used.

EDIT: After further fiddling, it also happens sometimes for commands that don't contain `<executor.markup.true>`. I can't tell anymore what exactly causes this to happen. But `<executor.markup.true>` causes it 100% of the time.

**Comment by raujonas** [comment]
Thanks for submitting your issue and sorry for the late reply. I was able to reproduce it, it seems like this line is responsible for the error: https://github.com/raujonas/executor/blob/641ef4f64e35388995873c0e2c6cf8d7148879d3/extension.js#L359

I was not able to solve it yet though. Even with the error in the console it is still working for me as expected (e.g. using the markup in the output). What is strange: if I wrap the problematic code in a try-catch block the error goes away, but also the output is not formatted using markup anymore, but at least I get a proper error message:

`Caught exception while setting use markup: TypeError: location.output[index].set_use_markup is not a function`

I can't find this function in the docs anymore but it still seems necessary to make the markup work :unamused: I'll keep trying to find a solution.

**Comment by mkalinski** [comment]
So I think I fixed it.

@raujonas Should I make a PR, or post an explanation here on what should be done?

**Comment by raujonas** [comment]
Whatever is best for you! PR would be appreciated of course, but you can also explain it and I'll try to create a fix as soon as possible.

**Comment by Ingineerix** [comment]
I too was having that problem, and it was a noticable hit to my battery life.  I applied @mkalinski's patch (Thanks!) and it fixed my problem.   Thanks to both of you!

Patch:  https://raw.githubusercontent.com/raujonas/executor/ee4125ecae308b9c9ba0c9b04723b0b9bb16ffca/extension.js

**Comment by raujonas** [comment]
Thanks again, it's now merged and available on EGO!
