### ISSUE TITLE
README.md for "documentation" branch

### ISSUE THREAD

**Issue by peter-kehl** [raujonas/executor#60]
Hi Jonas,

I'd be happy to create a PR for "documentation", but I don't know ho wit's generated, or what the formatting/generator technology is. 

Please provide README.md with steps to re-generarate, and with basic links about how it's written or what it uses, so that people can contribute PR's.

**Comment by raujonas** [comment]
Hi Peter,

sorry for the late reply. You're correct, I'll work on documenting this next. I also keep thinking about if we should move back the documentation to the main branch, having this on a separate branch just makes it more complex I think.

Best
Jonas
