### ISSUE TITLE
Add support for Gnome 45

### ISSUE THREAD

**Issue by Abdullah-2003** [raujonas/executor#70]
Please add support for gnome v45

**Comment by sjkl90** [comment]
I want to tell you that for me, it is the best extension that exists, I don't know anyone who can help, I wish I could... I want you to understand that the Gnome community needs this extension, I hope to be able to give my support, even if it is financially (not I have a lot) :D.

**Comment by Flimm** [comment]
This blog post on GNOME Shell's development blog looks relevant: [Extensions in GNOME 45 (2 Sept 2023)](https://blogs.gnome.org/shell-dev/2023/09/02/extensions-in-gnome-45/). Here's a quote:

> Extensions that target older GNOME versions will not work in GNOME 45. Likewise, extensions that are adapted to work with GNOME 45 will not work in older versions.
>
> You can still support more than one GNOME version, but you will have to upload different versions to [extensions.gnome.org](https://extensions.gnome.org/) for pre- and post-45 support.

Will pull requests that only work with GNOME 45 be accepted? It seems like it will be difficult to use the same codebase to support both GNOME 45 and earlier versions of GNOME.

**Comment by raujonas** [comment]
Thanks for all your effort and input! Yes, I think only making it compatible with Gnome 45 and removing the old code for new version will be the way to go. @Sierra410 already created a draft here #72 but I had no time to test it yet, hopefully today.
So if anyone wants to test the changes on his branch already, please feel free to do so! Hopefully we can get a compatible version up soon.

**Comment by sjkl90** [comment]
I'm trying it and it works perfectly for me. Thank you so much

**Comment by rouelle** [comment]
Same for me, everything works for now! As I use Gnome 45 (Arch Linux) with french Canada locale I can add that translation in french of Executor also works.

**Comment by tabascoz** [comment]
thanks - ti works ok for me on Gentoo Linux, gnome shell 45

**Comment by rouelle** [comment]
> [...] translation in french of Executor also works.

Just a small glitch for French: the last tab in Executor panel should be « Général » with accents;
also the option is not translated: « Click on output in top active bar » should be « Affichage au clic de la barre de statut »

Merci! Thanks!

**Comment by raujonas** [comment]
It's in review now in the store :wave:

**Comment by raujonas** [comment]
Ok, it was [rejected](https://extensions.gnome.org/review/46915) today, so I have to fix the findings and submit a new version, but it should not be that much effort. Sorry that it takes longer.

**Comment by Sierra410** [comment]
Looks like `this.settings = this.getSettings();` is the culprit?

I assume that the ExecutorPreferences instance is persistent, so by setting a member variable in it, the settings objects never gets garbage collected?  

The object should be made local to the method (`const settings = ...`) to fix it.

The object appears to be used in a few other methods. Some, like `clickOnOutputActiveClicked`, don't contain much logic at all and are wrapped in an arrow function anyway, so I propose to just remove them altogether and move the logic into the aforementioned arrow functions.  

So, this:
```js
clickOnOutputActive.connect('notify::active', () => {
	this.clickOnOutputActiveClicked(clickOnOutputActive.get_active());
});
```

Should be this:
```js
clickOnOutputActive.connect('notify::active', () => {
	settings.set_boolean('click-on-output-active', clickOnOutputActive.get_active());
});
```

`saveCommands()` method is relatively long, so it should be left as it, I think. In that case, the object should be passes as an argument.

By the way, most instances of `.bind(this)` can be removed by using arrow functions. e.g. `saveCommands = () => {...}`

**Comment by raujonas** [comment]
Thanks for your feedback @Sierra410, that is highly appreciated! I decided to only fix the issue mentioned in the review now so that you all get the new version asap. I'll then have a look at the bindings separately, I also noticed that there's an error happening sometimes when saving the settings.

If anyone wants to test the changes again, it's in #73

**Comment by raujonas** [comment]
It's now in review again :four_leaf_clover:

**Comment by raujonas** [comment]
It's available! Thanks for all your support again!

**Comment by Flimm** [comment]
Wonderful! Thank you so much. It's working well, here.
