### ISSUE TITLE
Don`t work in Gnome 46

### ISSUE THREAD

**Issue by scr4sh** [raujonas/executor#78]
Hello, as you may have noticed, it has stopped working in Gnome 46, thank you very much, we hope, as in every damn Gnome update, for your effort and we greatly appreciate it.

**Comment by raujonas** [comment]
Thanks for the feedback and letting me know, I'll start testing once the Beta of Fedora 40 is available, which is I think planned for later this week iirc.

**Comment by scr4sh** [comment]
I use arch linux, are you not going to update the code in the repository? Thx
