### ISSUE TITLE
Gnome 47 Support

### ISSUE THREAD

**Issue by scorpius2k1** [raujonas/executor#85]
Current version of executor incompatible with Gnome 47 and is automatically disabled.

Thank you for your time and efforts 🙂

![image](https://github.com/user-attachments/assets/cf6a0f83-4df6-433e-b7c6-037e3bb8f4e3)
![image](https://github.com/user-attachments/assets/ae6393b8-b8d6-45a3-9fdb-d235205fc448)

**Comment by rouelle** [comment]
Simply change "46" to "47" or add "47" to the shell-version section in your .local/share/gnome-shell/extensions/executor@raujonas.github.io/metadata.json file like this and executor works perfectly in gnome-shell 47 :-)

```
{
  "_generated": "Generated by SweetTooth, do not edit",
  "description": "Execute multiple shell commands periodically with separate intervals and display the output in
  "name": "Executor",
  "settings-schema": "org.gnome.shell.extensions.executor",
  "shell-version": [
    "46",
    "47"
  ],
  "url": "https://github.com/raujonas/executor",
  "uuid": "executor@raujonas.github.io",
  "version": 26
}

```

**Comment by scorpius2k1** [comment]
> Simply change "46" to "47" or add "47" to the shell-version section in your .local/share/gnome-shell/extensions/[executor@raujonas.github.io](mailto:executor@raujonas.github.io)/metadata.json file like this and executor works perfectly in gnome-shell 47 :-)
> 
> ```
> {
>   "_generated": "Generated by SweetTooth, do not edit",
>   "description": "Execute multiple shell commands periodically with separate intervals and display the output in
>   "name": "Executor",
>   "settings-schema": "org.gnome.shell.extensions.executor",
>   "shell-version": [
>     "46",
>     "47"
>   ],
>   "url": "https://github.com/raujonas/executor",
>   "uuid": "executor@raujonas.github.io",
>   "version": 26
> }
> ```

Thank you, this worked great until there is an official update available! In my case if it might be useful to someone, since the extension was installed via an arch package repo to my system, the path the the json file was:

`/usr/share/gnome-shell/extensions/executor@raujonas.github.io/metadata.json`

**Comment by raujonas** [comment]
The new version is in review now, should be available soon via extensions.gnome.org. Thanks for the heads up about the new version!
