### ISSUE TITLE
custom style doesn't work

### ISSUE THREAD

**Issue by JadeVane** [raujonas/executor#87]
Thank you for developing this extension, which gives my lame programming skills a place to shine.

I made a style change to the output result based on the documentation [here](https://raujonas.github.io/executor/docs/configuration/custom-markup/)

the key content of my script:

```bash
# Omit some irrelevant content here
...
echo "<span font_family='Monaco'>￪ $uploadSpeed   ￬ $downloadSpeed</span>"
```

but it did not take effect. Instead, the entire content was displayed directly on the panel.

Do you have any ideas?

**Comment by raujonas** [comment]
Hi @JadeVane, the custom style is only applied if it is enabled. It is enabled if the string `<executor.markup.true>` is somewhere in the command/output.

So please try this, this works for me:
`echo "<executor.markup.true><span font_family='Monaco'>￪ test1   ￬ test2</span>"`
![image](https://github.com/user-attachments/assets/707ad5db-98d0-4047-81b9-e6215bb92e3c)

I hope this helps, glad that you like the extension.
