### ISSUE TITLE
Better GUI for command settings

### ISSUE THREAD

**Issue by raujonas** [raujonas/executor#9]
Remove pasting the commands as a JSON string
Implement better GUI solution

**Comment by raujonas** [comment]
@peterrus what would you think about something like this?
![grafik](https://user-images.githubusercontent.com/25148277/91823184-1fdba200-ec39-11ea-891a-06ba6cca2f0b.png)

**Comment by raujonas** [comment]
Fresh from the oven, works but not deeply tested yet:
![grafik](https://user-images.githubusercontent.com/25148277/91907424-20f8e780-ecaa-11ea-8582-210be2bf60e3.png)

**Comment by raujonas** [comment]
@peterrus new version is now reviewed and in the official gnome repository!

**Comment by peterrus** [comment]
Alright gave it a test and I like it! Good job and thanks!

Only small issue I had is: It is not apparent that I can select a command row, so I didn't know why the 'remove' button was grayed out. Maybe give every row it's own remove button?

**Comment by raujonas** [comment]
@peterrus well.. try and click the small gap between the command and the interval selection :D But you're right that's not very intuitive. I'll add a fix so that the row gets selected if you enter the command box or change the interval.
